import os
import configparser
import logging

from .exceptions import Shutdown

log = logging.getLogger('turbo')


class Config:
    def __init__(self, filename):
        self.filename = filename
        if not os.path.isfile(filename):
            log.critical("{} does not exist".format(filename))
            raise Shutdown()

        try:
            config = configparser.ConfigParser(interpolation=None)
            config.read(filename, encoding='utf-8')
        except Exception as e:
            log.critical(str(e))
            raise Shutdown()

        # ---------------------------------------------------- #
        # DO NOT EDIT THIS FILE DIRECTLY. EDIT THE CONFIG FILE #
        # ---------------------------------------------------- #

        # [Auth]
        self.token = config.get('Auth', 'Token', fallback=None)

        # [General]
        self.prefix = config.get('General', 'Prefix', fallback='!')
        self.description = config.get('General', 'Description', fallback='Turbo (https://github.com/jaydenkieran/Turbo) is a selfbot developed using discord.py by Jayden.')
        self.not_found = config.get('General', 'NotFound', fallback='Invalid command: {}')

        log.debug("Loaded '{}'".format(filename))
        self.validate()

    def validate(self):
        """
        Checks configuration options for valid values
        """
        critical = False
        if not self.token:
            log.critical('You must provide a token in the config')
            critical = True
        if critical:
            raise Shutdown()
